'use strict';

var hello = 'Hello World';
console.log(hello);
typeof hello;
hello = 10;
typeof hello;
hello = false;
typeof hello;
hello = null;
typeof hello;
hello = undefined;
typeof hello;
hello = function() { console.log('Hello World'); }
typeof hello;
hello();
hello = function(numero) { console.log(numero); }
hello('Hello');
1+2;
1+'2';
1+2+'3';
'1'+2+3;
1+true;
hello = { nome: 'Hello', idade: 30 };
hello;
hello.nome;
hello.idade;
hello.nome = 'Hello World';
hello.filhos = ['Gohan', 'Goten'];
hello;
hello.filhos.constructor == Array;
false == '0';
false === '0';
10/2;
10/false;
10/'2';
10/'dois';
NaN == NaN;
isNaN(10/'2');
isNaN(10/'dois');
isNaN(10/'two');
10/'two';
[1,2,3].constructor == Array;
[1,2,3] instanceof Object;
[1,2,3] instanceof Array;
[1,2,3].constructor == Object;
if (typeof gohan !== 'undefined') { console.log('Ta definido'); } else { console.log('Nao');};
function isDefined(obj) { return typeof obj !== 'undefined';};
hello.filhos.push('Gothenks');
hello.hasOwnProporty('nome');
hello.hasOwnProporty('filhos');
